server:
  port: 8081


github:
  client:
    id: 4cd2a29bd24e314a3508
    secret: edebba4c19b56e0cfef43cc3c957b17dfc19e8c8
  redirect:
    uri: http://127.0.0.1:8081/callback

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:\Users\GQQQQQ\h2\community
    username: gqq
    password: 123456
  jpa:
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true